-- Supabase SQL Schema for Smart Price Tracker
-- Run this in the Supabase SQL Editor (https://supabase.com) to create or recreate the products table.

-- Drop existing tables to start fresh
drop table if exists public.price_history cascade;
drop table if exists public.products cascade;

-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  product_name text not null,
  category text not null,
  brand text not null,
  current_price numeric not null,
  original_price numeric not null,
  discount_percentage integer default 0,
  image_url text not null,
  product_description text,
  product_link text not null,
  source_website text not null,
  rating numeric default 4.0,
  stock_status text default 'In Stock',
  created_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Create policies for public access (select, insert, update, delete)
create policy "Allow public read on products"
  on public.products for select using (true);

create policy "Allow public insert on products"
  on public.products for insert with check (true);

create policy "Allow public update on products"
  on public.products for update using (true);

create policy "Allow public delete on products"
  on public.products for delete using (true);

-- Create index for faster querying
create index if not exists products_category_idx on public.products (category);
create index if not exists products_created_at_idx on public.products (created_at desc);

-- Create price_history table for tracking price changes over time
create table public.price_history (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  price numeric not null,
  recorded_at timestamptz default now()
);

-- Enable RLS and create policy for price_history
alter table public.price_history enable row level security;

create policy "Allow public read on price_history"
  on public.price_history for select using (true);

create policy "Allow public insert on price_history"
  on public.price_history for insert with check (true);
