-- Run in Supabase SQL Editor — extends products for real-time price tracking

alter table public.products
  add column if not exists original_price numeric,
  add column if not exists brand text,
  add column if not exists review_count integer default 0,
  add column if not exists external_id text,
  add column if not exists last_synced_at timestamptz;

create unique index if not exists products_source_external_uidx
  on public.products (source, external_id)
  where external_id is not null;

create index if not exists products_last_synced_idx
  on public.products (last_synced_at desc nulls last);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  price numeric not null,
  recorded_at timestamptz default now()
);

alter table public.price_history enable row level security;

create policy "Allow public read on price_history"
  on public.price_history for select using (true);

create policy "Allow public insert on price_history"
  on public.price_history for insert with check (true);
