-- Run this in the Supabase SQL Editor if the products table was deleted.
-- Dashboard + migrate_products.py expect these columns.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text,
  primary_image text,
  image_2 text,
  image_3 text,
  product_url text,
  source text,
  category text not null default 'General',
  description text,
  rating numeric default 4.0,
  discount integer default 0,
  original_price numeric,
  brand text,
  review_count integer default 0,
  external_id text,
  last_synced_at timestamptz,
  created_at timestamptz default now()
);

alter table public.products enable row level security;

-- Allow anon reads/writes (dev-friendly; tighten for production)
create policy "Allow public read on products"
  on public.products for select using (true);

create policy "Allow public insert on products"
  on public.products for insert with check (true);

create policy "Allow public update on products"
  on public.products for update using (true);

create policy "Allow public delete on products"
  on public.products for delete using (true);
